### ISSUE TITLE
APK

### ISSUE THREAD

**Issue by AmauryVanEspen** [metamaps/metamaps_mobile#1]
Good morning

i would like to know where i can find a .apk for android and iPhone

Thank you

Amaury

**Comment by Connoropolous** [comment]
hey Amaury! 

I'm a core dev on metamaps. We don't have a native android app or iphone app yet, this repository was a test version of a mobile app. We've just recently improved the mobile experience on the website a little bit. It is difficult as yet to create information on maps, but it is possible to browse around view them. I would love to know, what would you like to use a metamaps mobile app for?

**Comment by AmauryVanEspen** [comment]
Good morning Connoropolous,

Best wishes and happy new year =)

I was working with kind of "full digital environment" meeting room.
So, in that kind of place/space, there are lots of touchscreen. 
It would be very useful to be able to use metamaps through the digital screen.
Currently, the mobile embbeded system is sometime iOS, some other Android or windows mobile.

I know/believe, as i can connect with web browser, may it won't be a problem to use.

Let me know,
i would like to know more about metamaps and roadmap for 2017 and later.

Best

Amaury

**Comment by Connoropolous** [comment]
happy new year :) its great to hear from you. are you still working with this "full digital environment" meeting room? sounds exciting. 

we are working on a roadmap for metamaps currently, and we will share something in the online community we've started for Metamaps to outline it as it develops :) if you want to join the community, its on Hylo: https://www.hylo.com/c/metamaps

Right now there are some limitations to what you can do with metamaps on mobile. What would be the most useful thing to you to be able to do? And also more broadly, I'm wondering about what you are using metamaps for :)

**Comment by AmauryVanEspen** [comment]
Good afternoon Connor

I'm still working sometimes with this kind of environments.
I'm connecting to the Hylo Community.

I'm using MetaMaps for mapping ecosystem, relationship and ideas through co-creative design workshop for non-profits.

Related to the roadmap and features, i would like to suggest : 
- Export in RDF
- Git like history and versionning in order to track evolution of nodes and edges
- Cloud around items in order to group them for a visual analysis

I'm currently able to edit a map with Android => that rock's !

Moreover, we could discuss about related research paper if you are interested in this kind of subject.

Best

Amaury

**Comment by devvmh** [comment]
This repository is sort of defunct (no offense, Connor 😉 ) Let's move this discussion to our hylo community at https://hylo.com/c/metamaps.

I also created an RDF issue: https://github.com/metamaps/metamaps/issues/1015

We have internal discussions all the time about git-like history and versioning, but nothing is on the current roadmap. It will require some intense background work. We're all very committed to making it happen as resources become available to do it.

As for a visual cloud to group topics for visual analysis, that's a fine idea. Let's discuss it more

**Comment by Connoropolous** [comment]
@devvmh just to clarify about the history and versioning thing, as of December, we have been storing everything we need to be able to show a revision history, and relatedly, to set values back to what they previously were, but developing the user interface and user experience around it is really the hard part that's up next, but it's something I'd like to actively take on over the next few months.

**Comment by devvmh** [comment]
@connoropolous time to create an issue? :D
